config/routes.rb
Rabel::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}
  get 'settings' => 'users#edit'
  get 'member/:nickname' => 'users#show', :as => :member
  get 'member/:nickname/topics' => 'users#topics', :as => :member_topics
  post 'member/:nickname/follow' => 'users#follow', :as => :follow_user
  post 'member/:nickname/unfollow' => 'users#unfollow', :as => :unfollow_user
  put 'users/update_account' => 'users#update_account', :as => :update_account
  put 'users/update_password' => 'users#update_password', :as => :update_password
  put 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  get 'go/:key' => 'nodes#show', :as => :go
  get 't/:id' => 'topics#show', :as => :t
  get '/topics/:id' => redirect('/t/%{id}'), :constraints => { :id => /\d+/ }

  get 'my/topics' => 'users#my_topics', :as => :my_topics
  get 'my/following' => 'users#my_following', :as => :my_following
  get 'page/:key' => 'pages#show', :as => :page
  get 'goodbye' => 'welcome#goodbye'
  get 'captcha' => 'welcome#captcha'
  get 'sitemap' => 'welcome#sitemap'

  resources :nodes do
    resources :topics do
      member do
        get :move
        get :edit_title
        put :update_title
      end
    end
  end
  resources :topics do
    resources :comments
    resources :bookmarks
    post :preview, :on => :collection
    put :toggle_comments_closed
    put :toggle_sticky
    get :new_from_home, :on => :collection
    post :create_from_home, :on => :collection
  end

  resources :comments, :bookmarks, :upyun_images

  resources :notifications do
    get :read, :on => :member
  end

  namespace :admin do
    resources :planes do
      resources :nodes
      post :sort, :on => :collection
      get :sort, :on => :collection
    end

    resources :nodes do
      post :sort, :on => :collection
      get :move, :on => :member
      put :move_to, :on => :member
    end

    resources :users do
      member do
        put :toggle_admin
        put :toggle_blocked
      end
      resources :rewards
    end

    resources :pages do
      post :sort, :on => :collection
    end

    resource :site_settings
    resources :topics, :advertisements, :cloud_files, :rewards
    
    resources :notifications do
      delete :clear, :on => :collection
    end

    get 'appearance' => 'site_settings#appearance'

    root :to => 'welcome_admin#index'
  end
  root :to => 'welcome#index'

end

app/views/admin/pages/_form.html.haml
= simple_form_for [:admin, page], :html => {:class => 'form-horizontal'} do |f|
  = f.input :title, :label => '标题'
  .control-group
    = f.label :key, '英文标题', :class => 'control-label'
    .controls
      .input-prepend
        %span.add-on /page/
        = f.text_field :key, :class => 'input-small'
      %small.help-inline 只允许英文字符和下划线

  .control-group
    = f.label :content, '页面内容', :class => 'control-label'
    .controls
      = render 'shared/preview_widget', :ref => :page_content, :type => :page
      = f.text_area :content, :class => :span6, :rows => 5
  .control-group
    = f.label :published, '发布状态', :class => 'control-label'
    .controls
      %label.radio.inline
        = f.radio_button 'published', true
        %span.published 立刻发布
      %label.radio.inline
        = f.radio_button 'published', false
        %span.draft 保存为草稿
  .form-actions
    = f.submit '保存', :class => 'btn btn-small btn-primary'

app/views/admin/pages/_page.html.haml
%tr{:id => page.html_id}
  %td{:align => :right, :width => 200}
    = link_to page_real_url(page), page_real_url(page)
  %td{:align => :center, :width => :auto}
    = page.title
  %td{:align => :center, :width => :auto}
    = page_publish_status(page)
  %td{:align => :left}
    = admin_edit_button('修改页面', page)
    = admin_delete_button(page)

app/views/admin/pages/action.html.haml
.box
  .cell
    = build_admin_navigation([link_to('页面管理', admin_pages_path), @title])
  .inner
    = render 'form', :page => @page

app/views/admin/pages/index.html.haml
- content_for :template_js do
  :plain
    rabel.sortable("table tbody", "#{sort_admin_pages_path}", {
      helper: function(e, ui) {
        ui.children().each(function() {
          $(this).width($(this).width());
        });
        return ui;
      }
    })

.box
  .cell
    .fr
      = admin_create_button('创建新页面', :page)
    = build_admin_navigation([@title])
  .inner
    %table.table
      %thead
        %tr
          %th{:align => :right, :width => 100} URL
          %th{:align => :center, :width => :auto} 标题
          %th{:align => :center, :width => :auto} 发布状态
          %th{:align => :left} 操作
      %tbody
        = render @pages