config/routes.rb
Rabel::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}
  get 'settings' => 'users#edit'
  get 'member/:nickname' => 'users#show', :as => :member
  get 'member/:nickname/topics' => 'users#topics', :as => :member_topics
  post 'member/:nickname/follow' => 'users#follow', :as => :follow_user
  post 'member/:nickname/unfollow' => 'users#unfollow', :as => :unfollow_user
  put 'users/update_account' => 'users#update_account', :as => :update_account
  put 'users/update_password' => 'users#update_password', :as => :update_password
  put 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  get 'go/:key' => 'nodes#show', :as => :go
  get 't/:id' => 'topics#show', :as => :t
  get '/topics/:id' => redirect('/t/%{id}'), :constraints => { :id => /\d+/ }

  get 'my/topics' => 'users#my_topics', :as => :my_topics
  get 'my/following' => 'users#my_following', :as => :my_following
  get 'page/:key' => 'pages#show', :as => :page
  get 'goodbye' => 'welcome#goodbye'
  get 'captcha' => 'welcome#captcha'
  get 'sitemap' => 'welcome#sitemap'

  resources :nodes do
    resources :topics do
      member do
        get :move
        get :edit_title
        put :update_title
      end
    end
  end
  resources :topics do
    resources :comments
    resources :bookmarks
    post :preview, :on => :collection
    put :toggle_comments_closed
    put :toggle_sticky
    get :new_from_home, :on => :collection
    post :create_from_home, :on => :collection
  end

  resources :comments, :bookmarks, :upyun_images

  resources :notifications do
    get :read, :on => :member
  end

  namespace :admin do
    resources :planes do
      resources :nodes
      post :sort, :on => :collection
      get :sort, :on => :collection
    end

    resources :nodes do
      post :sort, :on => :collection
      get :move, :on => :member
      put :move_to, :on => :member
    end

    resources :users do
      member do
        put :toggle_admin
        put :toggle_blocked
      end
      resources :rewards
    end

    resources :pages do
      post :sort, :on => :collection
    end

    resource :site_settings
    resources :topics, :advertisements, :cloud_files, :rewards
    
    resources :notifications do
      delete :clear, :on => :collection
    end

    get 'appearance' => 'site_settings#appearance'

    root :to => 'welcome_admin#index'
  end
  root :to => 'welcome#index'

end

app/models/node.rb
# encoding: utf-8
class Node < ActiveRecord::Base
  include Sortable
  include Rabel::ActiveCache

  has_many :topics
  has_many :bookmarks, :as => :bookmarkable, :dependent => :destroy
  belongs_to :plane, :touch => true

  validates :name, :plane_id, :key, :presence => true
  validates :key, :uniqueness => true, :format => {:with => /[a-zA-Z0-9_-]+/, :message => I18n.t('tips.node_key_format')}
  validate :node_key_should_not_contain_slash

  attr_accessible :plane_id, :name, :key, :custom_css, :custom_html, :introduction, :position, :quiet

  def can_delete?
    self.topics_count == 0
  end

  private
    def node_key_should_not_contain_slash
      errors.add(:key, "不能包含斜线(/)") if self.key.present? and self.key.include?('/')
    end
end

app/controllers/admin/nodes_controller.rb
# encoding: utf-8
class Admin::NodesController < Admin::BaseController
  before_filter :find_parent_plane, :except => [:sort, :destroy, :move, :move_to]
  before_filter :find_node, :only => [:move, :move_to, :destroy]

  def new
    @node = @plane.nodes.new
    respond_to do |format|
      format.js {
        @title = '添加节点'
        render :show_form
      }
    end
  end

  def create
    @node = @plane.nodes.build(params[:node])
    respond_to do |format|
      if @node.save
        format.js
      else
        format.js { render :show_form }
      end
    end
  end

  def edit
    @node = @plane.nodes.find(params[:id])
    respond_to do |format|
      format.js {
        @title = '修改节点'
        render :show_form
      }
    end
  end

  def update
    @node = @plane.nodes.find(params[:id])
    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.js
      else
        format.js { render :show_form }
      end
    end
  end

  def sort
    params[:position].each_with_index do |id, pos|
      Node.update(id, :position => pos)
    end

    respond_to do |format|
      format.js { head :ok }
    end
  end

  def move
    respond_to do |f|
      f.js
    end
  end

  def move_to
    respond_to do |f|
      f.js {
        render :text => :error, :status => :unprocessable_entity unless @node.update_attributes(params[:node])
      }
    end
  end

  def destroy
    respond_to do |format|
      if @node.can_delete? and @node.destroy
        format.js
      else
        format.js { render :text => :error, :status => :unprocessable_entity }
      end
    end
  end
end

app/controllers/nodes_controller.rb
# encoding: utf-8
class NodesController < ApplicationController
  def show
    @node = Node.find_by_attr_cached!(:key, params[:key])
    @title = @node.name

    if params[:p].present?
      @page_num = params[:p].to_i
      @title += " (第 #{@page_num} 页)"
    else
      @page_num = 1
    end

    @total_topics = @node.topics_count
    @total_pages = (@total_topics * 1.0 / Siteconf.pagination_topics.to_i).ceil
    @next_page_num = (@page_num < @total_pages) ? @page_num + 1 : 0
    @prev_page_num = (@page_num > 1) ? @page_num - 1 : 0
    @topics = @node.cached_assoc_pagination(:topics, @page_num, Siteconf.pagination_topics.to_i, 'updated_at')

    @canonical_path = "/go/#{params[:key]}"
    @canonical_path += "?p=#{@page_num}" if @page_num > 1
    @seo_description = "#{@node.name} - #{@node.introduction}"

    respond_to do |format|
      format.html
      format.mobile { add_breadcrumb @node.name }
    end
  end
end

app/views/nodes/_bookmark_node.html.haml
%tr
  %td{:width => '50', :align => :right, :valign => :middle}
    .howmany= node.topics_count
  %td{:width => :auto, :align => :left}
    %h3= link_to node.name, go_path(node.key)

app/views/nodes/_bookmark_node.mobile.haml
.cell= link_to node.name, go_path(node.key)

app/views/nodes/_custom_fields.html.haml
- if node.custom_css.present?
  - content_for :final_head do
    %style{:type => 'text/css'}
      = node.custom_css.html_safe

- if node.custom_html.present?
  - content_for :rightbar do
    .box
      .inner
        = node.custom_html.html_safe

app/views/nodes/_item_node.html.haml
= link_to item_node.name, go_path(item_node.key), :class => :item_node

app/views/nodes/_node.html.haml
= link_to node.name, go_path(node.key), :class => "rabel item_node node_#{node.key}"

app/views/nodes/_node.mobile.haml
= link_to node.name, go_path(node.key), :style => 'font-size: 14px;'
&nbsp;&nbsp;

app/views/nodes/_paginator.html.haml
- if @total_pages > 1
  %ul.pager
    - if @prev_page_num > 0
      %li.previous
        - if @prev_page_num == 1
          = link_to '← 上一页', go_path(@node.key)
        - else
          = link_to '← 上一页', go_path(@node.key) + "?p=#{@prev_page_num}"
    %li.center
      %span.gray= "#{@page_num}/#{@total_pages}"

    - if @next_page_num > 0
      %li.next
        = link_to '下一页 →', go_path(@node.key) + "?p=#{@next_page_num}"

app/views/nodes/show.html.haml
- if user_signed_in?
  - content_for :template_js do
    $("a.super").click(function() { $("textarea.mll:first").focus() });

- if user_signed_in? and current_user.can_manage_site?
  - content_for :rightbar do
    .box
      .box-header
        节点管理
      .cell
        = link_to "修改 #{@node.name} 节点", admin_planes_path + "#!/click/edit_#{@node.html_id}", :class => 'btn btn-small btn-info'
      - if @node.quiet
        .inner
          = image_tag 'ghost.png', :align => :top, :title => t('tips.quiet_node')
          = t('tips.quiet_node')

= render 'custom_fields', :node => @node

.box
  .box-header
    .fr
      话题总数
      .label
        &nbsp;
        = @total_topics
        &nbsp;
    = build_navigation([@node.name], 'bigger')
    - if @node.introduction.present?
      .sep10
      %span.gray= @node.introduction
    - if user_signed_in?
      .sep10
      = link_to '创建新话题', '#new_topic', :class => 'btn btn-success'
      .sep5
  = render @topics
  .inner
    = render 'paginator'

- if user_signed_in?
  .box
    .box-header
      创建新话题
    .inner
      = render 'topics/form', :node => @node, :topic => @node.topics.new, :comments_closed => false

app/views/nodes/show.mobile.haml
- content_for :nav_right do
  = @total_topics
  个主题

- if user_signed_in?
  .cell
    = link_to new_node_topic_path(@node), :class => :btn do
      %input{:type => :button, :value => '创建新主题'}

= render @topics
- if @total_pages > 1
  .cell{:align => :center}
    = render :partial => 'paginator', :formats => :html

- if @node.custom_html.present?
  .cell= @node.custom_html.html_safe