config/routes.rb
Rabel::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}
  get 'settings' => 'users#edit'
  get 'member/:nickname' => 'users#show', :as => :member
  get 'member/:nickname/topics' => 'users#topics', :as => :member_topics
  post 'member/:nickname/follow' => 'users#follow', :as => :follow_user
  post 'member/:nickname/unfollow' => 'users#unfollow', :as => :unfollow_user
  put 'users/update_account' => 'users#update_account', :as => :update_account
  put 'users/update_password' => 'users#update_password', :as => :update_password
  put 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  get 'go/:key' => 'nodes#show', :as => :go
  get 't/:id' => 'topics#show', :as => :t
  get '/topics/:id' => redirect('/t/%{id}'), :constraints => { :id => /\d+/ }

  get 'my/topics' => 'users#my_topics', :as => :my_topics
  get 'my/following' => 'users#my_following', :as => :my_following
  get 'page/:key' => 'pages#show', :as => :page
  get 'goodbye' => 'welcome#goodbye'
  get 'captcha' => 'welcome#captcha'
  get 'sitemap' => 'welcome#sitemap'

  resources :nodes do
    resources :topics do
      member do
        get :move
        get :edit_title
        put :update_title
      end
    end
  end
  resources :topics do
    resources :comments
    resources :bookmarks
    post :preview, :on => :collection
    put :toggle_comments_closed
    put :toggle_sticky
    get :new_from_home, :on => :collection
    post :create_from_home, :on => :collection
  end

  resources :comments, :bookmarks, :upyun_images

  resources :notifications do
    get :read, :on => :member
  end

  namespace :admin do
    resources :planes do
      resources :nodes
      post :sort, :on => :collection
      get :sort, :on => :collection
    end

    resources :nodes do
      post :sort, :on => :collection
      get :move, :on => :member
      put :move_to, :on => :member
    end

    resources :users do
      member do
        put :toggle_admin
        put :toggle_blocked
      end
      resources :rewards
    end

    resources :pages do
      post :sort, :on => :collection
    end

    resource :site_settings
    resources :topics, :advertisements, :cloud_files, :rewards
    
    resources :notifications do
      delete :clear, :on => :collection
    end

    get 'appearance' => 'site_settings#appearance'

    root :to => 'welcome_admin#index'
  end
  root :to => 'welcome#index'

end

app/views/shared/_ad.html.haml
.box
  .inner
    %span{:style => 'font-weight: bold; font-size: 10px; color: #e2e2e2;'} Promotion
    .sep10
    = link_to ad.link, :class => :track_event, :target => '_blank', :data => {:category => :ad, :action => :click, :label => ad.title} do
      = image_tag ad.banner.url, :border => 0, :width => 120, :height => 90
    .sep5
    %span{:style => 'font-size: 11px; color: #666;'}
      %strong{:style => 'color: #000;'}
        = link_to ad.title, ad.link, :target => '_blank', :class => 'black track_event', :data => {:category => :ad, :action => :click, :label => ad.title}
    .sep3
    %span{:style => 'font-size: 12px;'}= ad.words

app/views/shared/_box_tip.html.haml
.glass
  .inner.center
    = tip

app/views/shared/_community_stats.html.haml
.box
  .box-header
    社区运行状态
  .inner
    %table{:cellpadding => 3, :cellspacing => 0, :border => 0, :width => '100%'}
      %tr
        %td{:align => :right, :width => 60}
          %span.gray 注册会员
        %td{:align => :left}
          %strong= User.cached_count
      %tr
        %td{:align => :right, :width => 50}
          %span.gray 话题
        %td{:align => :left}
          %strong= Topic.cached_count
      %tr
        %td{:align => :right, :width => 50}
          %span.gray 回复
        %td{:align => :left}
          %strong= Comment.cached_count

app/views/shared/_content.html.haml
- if flash_messages.any?
  .box
    .inner
      = show_flash_messages
= yield

app/views/shared/_fileupload_widget.html.haml
- if ENV['RABEL_UPYUN_SWITCH'] == 'on'
  - content_for :final_head do
    = javascript_include_tag 'i_fileupload'

  - content_for :template_js do
    :plain
      var textarea = $("#{textarea_selector}");
      var _tip = $("#upload-tip");
      $('#fileupload').fileupload({
          dataType: 'json',
          autoUpload: true,
          url: '/upyun_images.json',
          maxFileSize: 1024 * 1024 * 5,
          acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
          start: function(e) {
            _tip.html('图片上传中&nbsp;&middot;&middot;&middot;');
          },
          done: function (e, data) {
              $.each(data.result, function (index, file) {
                new_pic = "\n" + file.url;
                textarea.atCaret('insert', new_pic);
              });
          },
          always: function(e) {
            _tip.html("上传图片");
          },
      });

  .pull-right
    %a.fileupload-btn.action_label
      %span#upload-tip 上传图片
      %input#fileupload{:type => 'file', :multiple => true, :name => "upyun_image[asset][]"}

app/views/shared/_footer.html.haml
#footer
  .container#footer-main
    %ul.page-links
      = render :partial => 'pages/nav', :collection => Page.only_published.default_order, :spacer_template => 'pages/nav_ruler'
    .copywrite
      = Siteconf.footer.html_safe
    %small.muted
      Powered by
      = link_to 'Rabel', 'http://rabelapp.com', :target => '_blank', :class => :muted
      = Rabel.version

= render 'shared/google_analytics'

:javascript
  window.rabel.search_engine_url = "#{search_engine_url}";
  jQuery(function($) {
    #{yield :template_js}
  });

:javascript
  #{Siteconf.custom_js.html_safe}

app/views/shared/_google_analytics.html.haml
- if Rails.env.production? and Siteconf.ga_id.present?
  %script{:type => 'text/javascript'}
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', '#{Siteconf.ga_id}']);
    _gaq.push(['_trackPageview']);
    (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
- else
  / Google Analytics tracking code goes here

app/views/shared/_head.html.haml
= render 'shared/meta'
= stylesheet_link_tag "application"
= yield :head
- if Siteconf.theme != 'default'
  = stylesheet_link_tag "#{Siteconf.theme}/i_theme"
- if Siteconf.custom_css.present?
  %style{:type => 'text/css'}= Siteconf.custom_css.html_safe
= javascript_include_tag "application"
= yield :final_head

app/views/shared/_meta.html.haml
%meta{:name => 'description', :content => @seo_description}
%meta{:charset => 'UTF-8'}
%meta{:name => 'HandheldFriendly', :content => 'True'}
%meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1.0'}
%title= title
= Siteconf.custom_head_tags.html_safe
= favicon_link_tag
= auto_discovery_link_tag :atom, topics_path(:atom)
- if @canonical_path.present?
  %link{:rel => :canonical, :href => "http://'127.0.0.1'#{@canonical_path}"}
= csrf_meta_tags

app/views/shared/_my_fav.html.haml
%tr
  %td.with_separator{:width => '34%', :align => :center}
    = link_to my_topics_path, :class => :dark, :style => 'display: block;' do
      %span.bigger= current_user.bookmarked_topics_count
      .sep3
      %span.gray 话题收藏
  %td{:width => '33%', :align => :center}
    = link_to my_following_path, :class => :dark, :style => 'display: block;' do
      %span.bigger= current_user.followed_user_count
      .sep3
      %span.gray 特别关注

app/views/shared/_notification.html.haml
- action_user = notification.action_user
.cell
  %table{:width => '100%'}
    %tr
      %td{:width => 32, :align => :left, :valign => :top}
        = user_profile_avatar_link(action_user, :mini)
      %td{:valign => :top}
        %span.gray
          %strong= user_profile_link(action_user)
          - if notification.action == Notification::ACTION_REWARD
            - if notification.notifiable.amount > 0
              %span.green 奖励给你
            - else
              %span.red 从你的帐户中扣除了
            %strong= notification.notifiable.amount.abs
            = Siteconf.reward_title
          - else
            = notification.action_info_prefix
            = link_to notification.notifiable.notifiable_title, read_notification_path(notification), :class => :rabel
            = notification.action_info_suffix + '了你'
        %span.snow
          = time_ago_in_words(notification.created_at)
        .sep5
        - if notification.content.present?
          .payload= parse_markdown(notification.content)

app/views/shared/_preview_widget.html.haml
#preview-widget
  = link_to '编辑', 'javascript:void(0);', :class => 'action_label cancel_preview current_label', :data => {:ref => ref}
  = link_to '预览', 'javascript:void(0);', :class => 'action_label preview', :data => {:ref => ref, :type => type}
  #preview

app/views/shared/_rss.html.haml
= image_tag 'rss.png', :align => :absmiddle
= link_to 'RSS', topics_path(:atom), :target => '_blank', :class => :dark

app/views/shared/_top.html.haml
#TopMain
  - if Siteconf.custom_logo.present?
    = link_to root_path, :class => 'logo custom_logo' do
      = image_tag Siteconf.custom_logo, :alt => :logo
  - else
    = link_to Siteconf.site_name, root_path, :class => 'logo text_logo'
  #Navigation
    %ul
      %li= link_to '首页', root_path, :class => link_class
      - if user_signed_in?
        %li= user_profile_link(current_user, :class => link_class)
        %li= link_to '个人设置', settings_path, :class => link_class
        - if current_user.can_manage_site?
          %li= link_to '管理后台', admin_root_path, :class => link_class
        %li= link_to '登出', destroy_user_session_path, :method => :delete, :class => link_class
      - else
        %li= link_to '注册', new_user_registration_path, :class => link_class
        %li= link_to '登入', new_user_session_path, :class => link_class
  #Search
    .search_input
      %input#q{:type => 'text', :maxlength => 40, :name => 'q', :data => {:domain => Siteconf.site_host}}